name: module3_task5

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types: [opened, reopened]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Installing environment
        run: |
            cd module3_task5
            sudo ./setup.sh
      - name: Build
        run: |
            cd module3_task5
            make build
      - name: Post
        run: |
            cd module3_task5
            make POST_NAME=name POST_TITLE=title post
      - name: Package
        run: |
            cd module3_task5
            make package
      - name: Help
        run: |
            cd module3_task5
            make help
      - name: Clean
        run: |
            cd module3_task5
            make clean
      - name: Lint
        run: |
            cd module3_task5
            make lint
      - name: unittest
        run: |
            cd module3_task5
            make unit-tests
      - name: integration
        run: |
            cd module3_task5
            make integration-tests
      - name: validate
        run: |
            cd module3_task5
            make validate
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: hola
          path: module3_task5/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            module3_task5/DEPLOY.md
            module3_task5/awesome-website.zip
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './module3_task5/dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
